version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: apple-nest-api
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apple-nest-api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: